<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:env:generate-local',
    description: 'Generates an untracked .env.local file with an APP_SECRET and runtime defaults.',
)]
final class GenerateEnvLocalCommand extends Command
{
    public function __construct(private readonly string $projectDir)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('app-env', null, InputOption::VALUE_REQUIRED, 'APP_ENV value to write.', 'prod')
            ->addOption('app-debug', null, InputOption::VALUE_REQUIRED, 'APP_DEBUG value to write. Defaults to 0 for prod and 1 otherwise.')
            ->addOption('default-uri', null, InputOption::VALUE_REQUIRED, 'Optional DEFAULT_URI value for URLs generated from CLI commands.')
            ->addOption('force', 'f', InputOption::VALUE_NONE, 'Overwrite an existing .env.local file.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $environment = $this->stringOption($input, 'app-env');
        $debug = $this->debugValue($input, $environment);
        $defaultUri = $this->nullableStringOption($input, 'default-uri');
        $path = $this->projectDir.\DIRECTORY_SEPARATOR.'.env.local';

        if ('' === $environment) {
            $io->error('The --app-env option cannot be empty.');

            return Command::INVALID;
        }

        if (null === $debug) {
            $io->error('The --app-debug option must be 0, 1, true, false, on, off, yes, or no.');

            return Command::INVALID;
        }

        if (file_exists($path) && true !== $input->getOption('force')) {
            $io->error('.env.local already exists. Re-run with --force to overwrite it.');

            return Command::FAILURE;
        }

        $contents = $this->buildEnvLocalContents($environment, $debug, $defaultUri);
        if (false === file_put_contents($path, $contents, \LOCK_EX)) {
            $io->error(sprintf('Could not write %s.', $path));

            return Command::FAILURE;
        }

        @chmod($path, 0600);

        $io->success(sprintf('Generated %s.', $path));
        $io->note('Keep this file out of git. It contains the app secret for this installation.');

        return Command::SUCCESS;
    }

    private function stringOption(InputInterface $input, string $name): string
    {
        $value = $input->getOption($name);

        return \is_scalar($value) ? trim((string) $value) : '';
    }

    private function nullableStringOption(InputInterface $input, string $name): ?string
    {
        $value = $this->stringOption($input, $name);

        return '' === $value ? null : $value;
    }

    private function debugValue(InputInterface $input, string $environment): ?string
    {
        $debug = $this->nullableStringOption($input, 'app-debug');
        if (null === $debug) {
            return 'prod' === $environment ? '0' : '1';
        }

        return match (strtolower($debug)) {
            '0', 'false', 'off', 'no' => '0',
            '1', 'true', 'on', 'yes' => '1',
            default => null,
        };
    }

    private function buildEnvLocalContents(string $environment, string $debug, ?string $defaultUri): string
    {
        $lines = [
            '# Generated by php bin/console app:env:generate-local.',
            '# This file is intentionally untracked and should contain installation-specific values.',
            sprintf('APP_ENV=%s', $this->dotenvValue($environment)),
            sprintf('APP_DEBUG=%s', $this->dotenvValue($debug)),
            sprintf('APP_SECRET=%s', $this->dotenvValue(bin2hex(random_bytes(32)))),
        ];

        if (null !== $defaultUri) {
            $lines[] = sprintf('DEFAULT_URI=%s', $this->dotenvValue($defaultUri));
        }

        return implode("\n", $lines)."\n";
    }

    private function dotenvValue(string $value): string
    {
        if (1 === preg_match('/^[A-Za-z0-9_.:\/-]+$/', $value)) {
            return $value;
        }

        $escaped = str_replace(
            ['\\', '"', "\n", "\r"],
            ['\\\\', '\\"', '\\n', '\\r'],
            $value,
        );

        return '"'.$escaped.'"';
    }
}
